### PR TITLE
Create pies

### LINKED ISSUE #5: JS: Grab the values from the form on button click
# User Story

# Acceptance Criteria

# Dependecies

# Dev Notes

### LINKED ISSUE #21: JS: Add the NEW pie to the DOM and reset the form fields on submission

### PR DESCRIPTION
**Pull request by drteresavasquez**
## Description
Fixes #5 
Fixes #21 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by TrinityChristiana** [comment]
Needs to be merged into pies not main.

**Review by ajawashington — CHANGES_REQUESTED** [review]
merging into main or pies?

**Review by TrinityChristiana — APPROVED** [review]
😎

**Review by ajawashington — APPROVED** [review]
💯

**Pull request merged**
